server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/orders/**
        - id: products-service1
          uri: http://localhost:19093
          predicates:
            - Path=/products/**
            - Weight=group-products, 7
        - id: products-service
          uri: http://localhost:19094
          predicates:
            - Path=/products/**
            - Weight=group-products, 3
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}